# Configuración de Ruff
target-version = "py311"
line-length = 88

[lint]
# Reglas seleccionadas:
# E: pycodestyle (estilo estándar)
# F: Pyflakes (errores lógicos)
# B: flake8-bugbear (posibles bugs)
# I: isort (orden de los imports)
select = ["E", "F", "B", "I"]

# Reglas que ignoramos para facilitar el desarrollo inicial
ignore = [
    "E501", # Ignorar líneas demasiado largas (ya que a veces las URLs son largas)
    "B008", # Permitir declarar Depends() en los argumentos de FastAPI
]

[format]
# Usar comillas dobles, similar a Black
quote-style = "double"
indent-style = "space"